21 igpublishermetadata
HL7Austria/hl7-at-fhir-profiles pull request #37
Opened 2020-09-17 14:05 UTC by Nik-xT

2020-09-18 10:32 UTC, oliver-krauss approved these changes

2020-09-22 17:12 UTC, regelkraut requested changes
Please revert the changes for the ISO 21090 extensions. These are the official ones which we copied into the repo to be on the safe side. So the id for these extensions must remain unchanged to the official definition, see for example: http://hl7.org/fhir/stu3/extension-iso21090-adxp-streetname.json.html

2020-09-27 11:45 UTC, aschuler84 approved these changes

2020-09-28 05:50 UTC, Nik-xT commented
changes for the ISO 21090 extensions have been reverted

2020-09-28 12:31 UTC, regelkraut approved these changes

2020-09-28 12:31 UTC, merged